Review README up to DockerHub guidance.
DanielEgan/ContainerTraining pull request #2
Opened 2022-05-23 17:08 UTC by KatieProchilo

Hey Daniel, most changes are formatting changes throughout the entire README:

- Convert `<pre><code>` tags to use the appropriate equivalent like ```c# instead. Better syntax highlighting this way
- Spelling fixes

As far as reviewing the actual content, only got up to "Uploading to Docker Hub." This diff looks to be a bit of a pain so I'll try and comment any actual content changes.

2022-05-23 17:25 UTC, KatieProchilo commented on README.md
> +```
This is new, a change to reflect .NET 6

2022-05-23 17:26 UTC, KatieProchilo commented on README.md
> +the Dockerfile too to allow it to be accessed in the cloud.
Slight rewording to reflect code changes below

2022-05-23 17:33 UTC, KatieProchilo commented on README.md
> +> **_NOTE:_** Bash users might get an error like "the input device is not a TTY. If you are using mintty, try prefixing
This note is all new. Do you want to keep it? It's specific guidance for bash users that wasn't terribly hard to figure out

2022-05-23 17:36 UTC, KatieProchilo commented on README.md
> +docker run -it --rm -p 5000:5000 --name To_Do_App --entrypoint bash todov1
New, previous command (`docker run -it --rm -p 5000:5000  --name ToDo_App --entrypoint /bin/bash todov1 `) didn't work. Name was wrong but also `--entrypoint /bin/bash` seemed out of date

2022-05-23 17:37 UTC, KatieProchilo commented on README.md
> +## Uploading to Docker Hub
Starting here, all the content is the same as before. I'll make a new PR later with content edits

2022-05-23 17:39 UTC, KatieProchilo commented on README.md
> --> docker build -t todov1 .
Removed all the `-->` that were prefixed to commands so that users can easily copy and paste into their terminal with GitHub's clipboard button

2022-06-07 14:47 UTC, DanielEgan commented on README.md
> +- Running the container in Azure using ACI (Azure Container Service)
This was my original error but it should be ( Azure Container Instance )

2022-06-07 14:52 UTC, DanielEgan commented on README.md
> +The first thing we need to to set up an ASP.NET Core Web API to have something to call when we testing out containers. For our purposes, this needs to be ASP.NET Core since we will be using kubernete
repeated to..... The first thing we need to to... should be to do

Also this :    when we testing out containers...... should be....    when we are testing our

2022-06-07 15:13 UTC, DanielEgan commented on README.md
> +```bash
We can remove the middle steps as long as we say something like. your output will look something like this.

2022-06-07 15:14 UTC, DanielEgan requested changes
Just some minor changes. Looks great.

2022-06-27 17:19 UTC, merged